language: python
python:
  - "2.7"
cache:
  directories:
    - /home/travis/virtualenv/python2.7
install:
  - pip install flake8
  - pip install -r requirements.txt
before_script:
  - flake8 .
  - psql -c 'create database restaurants_db;’ -U postgres
script:
  - ./manage.py test
