language: python
python:
  - "2.7"

install: pip install -r requirements.txt --quiet

jobs:
  include:
    - script: pip install flake8 --quiet && flake8 .
    - script: python ./manage.py test

notifications:
    slack: rv-025lamp:t8bhwuryQcH8AdBDbDOoiwMQ
