language: python
python:
  - "2.7"
install:
  - pip install flake8
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
script:
  - flake8 cmdbox
  - coverage run manage.py test --settings=cmdbox.tests_settings
after_success:
  - coveralls
