# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('read_user', 'Can read information about user'),)},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, b'user'), (1, b'admin'), (3, b'manager'), (4, b'submanager')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text="Use just numbers: '380931234567", max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, b'active'), (1, b'deleted'), (3, b'banned'), (4, b'unauthorized')], default=0),
        ),
    ]
