# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20170711_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
