# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('logo', models.CharField(default=b'Logo_added', max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('status', models.IntegerField(choices=[(0, b'active'), (1, b'deleted'), (2, b'hidden')], default=0)),
                ('tables_count', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_type', models.CharField(max_length=256)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.RestaurantType'),
        ),
    ]
