# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 09:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(default=b'Logo_added', max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('status', models.IntegerField(choices=[(0, b'active'), (1, b'deleted'), (2, b'hidden')], default=0)),
                ('tables_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(max_length=256)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('rest_type', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Restaurant type',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.RestaurantType'),
        ),
    ]
