# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Restaurant_profile',
        ),
        migrations.RenameModel(
            old_name='RestaurantType',
            new_name='Restaurant_type',
        ),
    ]
