# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20170712_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant_profile',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AlterModelOptions(
            name='restaurant_type',
            options={'verbose_name': 'Restaurant type'},
        ),
        migrations.AlterField(
            model_name='restaurant_profile',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='restaurant_profile',
            name='tables_count',
            field=models.IntegerField(),
        ),
    ]
