# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20170712_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_profile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
